name: sast-secret

on:
  push:
    branches:
      - master

  
jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master

  horusec-security:
    name: horusec-security
    runs-on: ubuntu-20.04
    needs: gitleaks
    steps:
      - name: check out code into the go module dir
        uses: actions/checkout@v3
      - name: Running horusec download latest version
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" --config-file-path horusec-config.json -o="json" -O="./report.json"
      - name: upload sec scan result artifact
        uses: actions/upload-artifact@v3
        with:
          name: horusec
            #path: horusec-config.json
          path: report.json