name: Snyk SAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
#  schedule:
#    - cron: '28 13 * * 1'

#permissions:
#  contents: read

jobs:
  snyk-code:
#    permissions:
#      contents: read # for actions/checkout to fetch code
#      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
#      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    name: Snyk Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: >
          --severity-threshold=high
          --all-projects
          --sarif-file-output=snyk-code.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif

snyk-container:
  name: Snyk Container
  runs-on: ubuntu-latest
  needs: snyk-code
  steps:
    ## Checkout is required since Snyk needs the Dockerfile for the Sarif report
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Docker Build
      run: |
        docker build -t image-snyk:${{ github.sha }} . 
    - name: Snyk
      uses: snyk/actions/docker@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: image-snyk:${{ github.sha }}
        args: >
          --file=Dockerfile
          --severity-threshold=high
    - name: Upload SARIF file
      #if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif